config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Main Views
  root 'home#index'
  get 'home/index', to: 'home#index', as: 'home'
  get 'audit_activities/index'
  get 'dashboard', to: 'dashboards#index'

  # Authentication
  get '/users/:id', to: 'users#show', as: 'user'
  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/training_activities/chart', to: 'training_activities#chart_data', as: 'chart_data'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :training_activities
  resources :user
  resources :audit_activities do
    member do
      post :approve
      post :improve
      post :reject
      post :resubmit
      post :cancel
    end
  end
  resources :admin do
    collection do
      post :import
      post :stop_impersonate
    end
    member do
      post :impersonate
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/_form.html.erb
<%= form_with(model: @user, local: false, "data-turbo": "true", html: {class: "", id: "admin_form"}, url: {controller: "admin", action: @user.new_record? ? "create" : "update"}, method: @user.new_record? ? :post : :patch) do |form| %>
  <div class="row mb-3">
    <div class="col">
      <%= form.label :first_name, "First Name", class: "form-label" %>
      <div data-mdb-input-init class="form-outline">
        <%= form.text_field :first_name, required: true, class: "form-control" %>
      </div>
    </div>
    <div class="col">
      <%= form.label :last_name, "Last Name", class: "form-label" %>
      <div data-mdb-input-init class="form-outline">
        <%= form.text_field :last_name, required: true, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
    <%= form.label :email, "Email", class: "form-label" %>
    <div data-mdb-input-init class="form-outline">
      <%= form.text_field :email, required: true, class: "form-control" %>
    </div>
    </div>
  </div>
  
  <%= form.label :unit_id, "Outfit", class: "form-label" %>
  <div class="select-outline">
    <%= form.select :unit_id, 
        Unit.where(cat: "outfit").map{ |unit| [unit.name, unit.id]},
        {prompt: "Choose Outfit"},
        {required: true, class: "select form-control", data: {mdb_select_init: true}} %>
  </div>
  <div class="form-check">
    <%= form.check_box :admin_flag, class: "form-check-input", id: "admin_flag" %>
    <%= form.label :admin_flag, class: "form-check-label", for: "admin_flag" do %>
      Admin User
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/admin/edit.html.erb
<h1>Edit User Information</h1>
<%= render "form", user: @user %>
<br>
<%= link_to "Back", admin_path, class: "btn btn-secondary" %>
    

app/views/admin/index.html.erb
<div class="header">
  <%= link_to "Create New User", new_admin_path, class: "btn btn-success" %>

  <div class="search-bar">
    <%= form_tag(admin_index_path, method: :get) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<br>

<div class="table-responsive">
  <table id="usersTable" class="table table-striped table-hover align-middle">
    <thead class="table-light">
      <tr>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Outfit</th>
        <th scope="col">Minor Unit</th>
        <th scope="col">Major Unit</th>
        <th scope="col" class="text-center align-middle">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= user.unit_name %></td>
          <td><%= user.minor %></td>
          <td><%= user.major %></td>
          <td class="text-center align-middle">
            <%= link_to admin_path(id: user.id) do %>
              <%= content_tag(:i, '', class: "fa fa-eye") %>
            <% end %>
            <%= form_tag impersonate_admin_path(id: user.id), method: :post do %>
              <%= submit_tag "Impersonate", class: "btn btn-primary" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
</div>
<br>
<div> 
  <h2> Upload User Data from CSV</h2>
  <%= form_with url: import_admin_index_path, method: :post do |form| %>
    <%= form.file_field :file, accept: ".csv" %>
    <%= form.button "Import" %>
  <% end %>
</div>

app/views/admin/new.html.erb
<h1>New User Data</h1>
<%= render "form", user: @user %>
<br>
<%= link_to "Back", admin_index_path,  class: "btn btn-secondary" %>

app/views/admin/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      User Details
    </div>
    <div class="card-body">
      <p class="card-text"><strong>First Name:</strong> <%= @user.first_name %></p>
      <p class="card-text"><strong>Last Name:</strong> <%= @user.last_name %></p>
      <p class="card-text"><strong>Email:</strong> <%= @user.email %></p>
      <p class="card-text"><strong>Unit:</strong> <%= @user.unit_name %></p>
      <p class="card-text"><strong>Minor Unit:</strong> <%= @user.minor %></p>
      <p class="card-text"><strong>Major Unit:</strong> <%= @user.major %></p>

    <div class="card-footer">
      <%= link_to "Edit", edit_admin_path(id: @user.id), class: "btn btn-primary" %>
      <%= button_to "Delete", admin_path(id: @user.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", form_class: "d-inline" %>
      <%= link_to "Back", admin_index_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>