config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Main Views
  root 'home#index'
  get 'home/index', to: 'home#index', as: 'home'
  get 'audit_activities/index'
  get 'dashboard', to: 'dashboards#index'

  # Authentication
  get '/users/:id', to: 'users#show', as: 'user'
  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/training_activities/chart', to: 'training_activities#chart_data', as: 'chart_data'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :training_activities
  resources :user
  resources :audit_activities do
    member do
      post :approve
      post :improve
      post :reject
      post :resubmit
      post :cancel
    end
  end
  resources :admin do
    collection do
      post :import
      post :stop_impersonate
    end
    member do
      post :impersonate
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/training_activity.rb
# frozen_string_literal: true

class TrainingActivity < ApplicationRecord
  include AASM
  belongs_to :user
  belongs_to :unit

  attr_accessor :current_user, :comment

  has_one_attached :opord_upload
  has_and_belongs_to_many :competencies
  has_many :activity_histories, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :date, presence: true
  validates :time, presence: true, inclusion: { in: %w[MA AA] }
  validates :location, presence: true
  validates :priority, presence: true
  validates :justification, presence: true
  validates :unit_id, presence: true

  validate :validate_date
  validate :validate_competencies
  validate :validate_opord_upload_size
  validate :validate_opord_upload_type

  aasm column: 'status' do
    state :pending_minor_unit_approval, initial: true, display: 'Pending Minor Unit Approval'
    state :pending_major_unit_approval, display: 'Pending Major Unit Approval'
    state :pending_commandant_approval, display: 'Pending Commandant Approval'
    state :approved, display: 'Approved'
    state :revision_required_by_submitter, display: 'Revision Required by Submitter'
    state :revision_required_by_minor_unit, display: 'Revision Required by Minor Unit'
    state :revision_required_by_major_unit, display: 'Revision Required by Major Unit'
    state :rejected, display: 'Rejected'
    state :cancelled, display: 'Cancelled'

    # Event: Approved by Minor Unit; Submitted for Major Unit Approval
    event :submit_for_major_unit_approval do
      transitions from: :pending_minor_unit_approval, to: :pending_major_unit_approval do
        success do
          log_activity_history('submitted_for_major_unit_approval')
          send_pending_approval_email('major')
        end
      end
    end

    # Event: Approved by Major Unit; Submitted for Commandant Approval
    event :submit_for_commandant_approval do
      transitions from: :pending_major_unit_approval, to: :pending_commandant_approval do
        success do
          log_activity_history('submitted_for_commandant_approval')
          send_pending_approval_email('cmdt')
        end
      end
    end

    # Event: Approved by Commandant; Training Activity Approved
    event :approved do
      transitions from: :pending_commandant_approval, to: :approved do
        success do
          log_activity_history('approved', comment)
        end
      end
    end

    # Revision Required by Submitter; Requested by Minor Unit
    event :request_submitter_revision do
      transitions from: %i[pending_minor_unit_approval pending_major_unit_approval pending_commandant_approval revision_required_by_minor_unit revision_required_by_major_unit],
                  to: :revision_required_by_submitter do
        success do
          log_activity_history('revision_required_by_submitter', comment)
          send_revision_email
        end
      end
    end

    # Revision Required by Minor Unit; Requested by Major Unit
    event :request_minor_unit_revision do
      transitions from: %i[pending_major_unit_approval pending_commandant_approval revision_required_by_major_unit], to: :revision_required_by_minor_unit do
        success do
          log_activity_history('revision_required_by_minor_unit', comment)
          send_revision_email
        end
      end
    end

    # Revision Required by Major Unit; Requested by Commandant
    event :request_major_unit_revision do
      transitions from: %i[pending_commandant_approval], to: :revision_required_by_major_unit do
        success do
          log_activity_history('revision_required_by_major_unit', comment)
          send_revision_email
        end
      end
    end

    # Event: Submitted for Minor Unit Approval from Revision Required by Submitter
    event :submit_for_minor_unit_approval do
      transitions from: :revision_required_by_submitter, to: :pending_minor_unit_approval do
        success do
          log_activity_history('revision_submitted_for_minor_unit_approval', comment)
          send_pending_approval_email('minor')
        end
      end
    end

    # Event: Submitted for Major Unit Approval from Revision Required by Minor Unit
    event :submit_for_major_unit_approval_from_minor_unit_revision do
      transitions from: :revision_required_by_minor_unit, to: :pending_major_unit_approval do
        success do
          log_activity_history('revision_submitted_for_major_unit_approval', comment)
          send_pending_approval_email('major')
        end
      end
    end

    # Event: Submitted for Commandant Approval from Revision Required by Major Unit
    event :submit_for_commandant_approval_from_major_unit_revision do
      transitions from: :revision_required_by_major_unit, to: :pending_commandant_approval do
        success do
          log_activity_history('revision_submitted_for_commandant_approval', comment)
          send_pending_approval_email('cmdt')
        end
      end
    end

    # Event: Rejected
    event :reject do
      transitions from: %i[pending_minor_unit_approval pending_major_unit_approval pending_commandant_approval], to: :rejected do
        success do
          log_activity_history('rejected', comment)
          send_rejected_email
        end
      end
    end

    # Event: Cancelled
    event :cancel do
      transitions from: %i[pending_minor_unit_approval pending_major_unit_approval pending_commandant_approval request_minor_unit_revision request_submitter_revision request_major_unit_revision approved],
                  to: :cancelled do
        success do
          log_activity_history('cancelled', comment)
        end
      end
    end
  end

  after_create :send_initial_approval_request, if: -> { status == 'pending_minor_unit_approval' }

  # Send email to minor unit staff when activity is created
  def send_initial_approval_request
    send_pending_approval_email('minor')
  end

  def log_activity_history(event, comment = 'No Reason Provided.')
    message = case event
              when 'activity_created'
                "Training Activity Created by #{current_user.first_name} (#{current_user.email}). Requesting Minor Unit Approval."
              when 'submitted_for_major_unit_approval'
                "Minor Unit Approval by #{current_user.first_name} (#{current_user.email}). Requesting Major Unit Approval."
              when 'submitted_for_commandant_approval'
                "Major Unit Approval by #{current_user.first_name} (#{current_user.email}). Requesting Commandant Approval."
              when 'approved'
                "Commandant Approval by #{current_user.first_name} (#{current_user.email}). Training Activity Approved."
              when 'revision_required_by_submitter'
                "Revision Required by #{current_user.first_name} (#{current_user.email}). Requesting Submitter Revision."
              when 'revision_required_by_minor_unit'
                "Revision Required by #{current_user.first_name} (#{current_user.email}). Requesting Minor Unit Revision."
              when 'revision_required_by_major_unit'
                "Revision Required by #{current_user.first_name} (#{current_user.email}). Requesting Major Unit Revision."
              when 'revision_submitted_for_minor_unit_approval'
                "Revision Submitted by #{current_user.first_name} (#{current_user.email}). Requesting Minor Unit Approval."
              when 'revision_submitted_for_major_unit_approval'
                "Revision Submitted by #{current_user.first_name} (#{current_user.email}). Requesting Major Unit Approval."
              when 'revision_submitted_for_commandant_approval'
                "Revision Submitted by #{current_user.first_name} (#{current_user.email}). Requesting Commandant Approval."
              when 'rejected'
                "Rejected by #{current_user.first_name} (#{current_user.email}). #{comment.presence || 'No comment provided.'}"
              when 'cancelled'
                "Cancelled by #{current_user.first_name} (#{current_user.email}). #{comment.presence || 'No comment provided.'}"
              else
                "#{event.humanize} by #{current_user.first_name} (#{current_user.email})."
              end

    activity_histories.create(event: message, user: current_user, comment:)
  end

  # Find users to send emails based on which upper level
  # param cat should be minor/major/cmdt
  def send_pending_approval_email(cat)
    goal_unit = unit.get_parent_by_cat(cat)

    return unless goal_unit

    # puts "goal unit: #{goal_unit.name}, unit_id: #{goal_unit.id}"
    staff_users = User.where('unit_id = ? AND unit_name LIKE ?', goal_unit.id, '%Staff%')
    # puts "Found staff_users: #{staff_users.map(&:email)}" # Check if users are correctly fetched

    staff_users.each do |user|
      # puts "Sending email to: #{user.email}, Unit ID: #{user.unit_id}" # Debug information
      TrainingActivitiesMailer.pending_approval_notification(self, user).deliver_later
    end
  end

  def send_revision_email
    # puts "Sending revision notification: #{user.email}"
    TrainingActivitiesMailer.revision_notification(self).deliver_later
  end

  def send_rejected_email
    TrainingActivitiesMailer.rejected_notification(self).deliver_later
  end

  private

  def validate_date
    errors.add(:date, 'must be in the future.') if date < Date.today
    errors.add(:date, 'year must be four digits.') unless date.year.to_s.length == 4
  end

  def validate_competencies
    # Only up to 3 competencies can be selected
    return unless competency_ids.count > 3

    errors.add(:competency_ids, 'You can only select up to 3 competencies.')
  end

  def validate_opord_upload_size
    return unless opord_upload.attached? && opord_upload.blob.byte_size > 5.megabytes

    errors.add(:opord_upload, 'is too large. Maximum size is 5MB.')
  end

  def validate_opord_upload_type
    return unless opord_upload.attached? && !opord_upload.content_type.in?(%w[application/pdf])

app/controllers/training_activities_controller.rb
# frozen_string_literal: true

class TrainingActivitiesController < ApplicationController
  include TrainingActivitiesHelper
  before_action :set_training_activity, only: %i[show edit update destroy]

  # GET /training_activities
  def index
    # @units = current_user.units.flat_map(&:units).uniq
    unit_list = [current_user.unit] + current_user.unit.all_descendants
    # unit_list.each do |unit|
    #   puts "Unit Name: #{unit.name}, Unit ID: #{unit.id}"
    # end
    @training_activities = TrainingActivity.includes(:activity_histories).where(unit: unit_list)
  end

  def chart_data
    month = Date.today.beginning_of_year.change(month: params[:month].to_i) if params[:month].present? && params[:month].to_i.between?(1, 12)
    status_order = %w[pending_minor_unit_approval pending_major_unit_approval
                      pending_commandant_approval approved revision_required_by_submitter
                      revision_required_by_minor_unit revision_required_by_major_unit rejected cancelled]
    month_number = params[:month].to_i
    if params[:month].blank?
      @month_name = 'All Months'
      unordered_data = TrainingActivity.group(:priority, :status).count
    elsif (1..12).cover?(month_number)
      @month_name = Date::MONTHNAMES[month_number]
      unordered_data = TrainingActivity.where(date: month.beginning_of_month..month.end_of_month).group(:priority, :status).count
    else
      @month_name = 'Invalid Month'
      unordered_data = {}
    end
    @data = unordered_data.sort_by { |(priority, status), _| [priority, status_order.index(status)] }.to_h
    render :chart
  end

  def show; end

  # GET /training_activities/new
  def new
    @training_activity = TrainingActivity.new
  end

  # POST /training_activities
  def create
    @training_activity = TrainingActivity.new(training_activity_params)
    @training_activity.current_user = current_user
    @training_activity.update(user_id: session[:user_id])

    respond_to do |format|
      if @training_activity.save
        handle_successful_save(format)
      else
        handle_failed_save(format)
      end
    end
  end

  # GET /training_activities/1/edit
  def edit; end

  # PATCH/PUT /training_activities/1
  def update
    if @training_activity.update(training_activity_params)
      redirect_to @training_activity, notice: 'Training Activity as successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /training_activities/1
  def destroy
    @training_activity.destroy
    redirect_to training_activities_url, notice: 'Training Activity was successfully destroyed.'
  end

  # These have not been implemented yet, placeholder functions for when audit is merged
  #   def minor_unit_approval
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.submit_for_major_unit_approval!
  #     TrainingActivitiesMailer.major_unit_approval(@training_activity).deliver_now
  #   end
  #
  #   def major_unit_approval
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.submit_for_commandant_approval!
  #     TrainingActivitiesMailer.commandant_approval(@training_activity).deliver_now
  #   end
  #
  #   def minor_unit_revision_required(params[:id])
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.require_minor_unit_revision!
  #     TrainingActivitiesMailer.minor_unit_revision(@training_activity).deliver_now
  #   end
  #
  #   def major_unit_revision_required(params[:id])
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.require_major_unit_revision!
  #     TrainingActivitiesMailer.major_unit_revision(@training_activity).deliver_now
  #   end
  #
  #   def submitter_revision_required(params[:id])
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.require_submitter_revision!
  #     TrainingActivitiesMailer.submitter_revision(@training_activity).deliver_now
  #   end
  #
  #   def approved
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.approve!
  #     TrainingActivitiesMailer.approved(@training_activity).deliver_now
  #   end
  #
  #   def rejected
  #     @training_activity = TrainingActivity(params[:id])
  #     @training_activity.comment = params[:comment]
  #     @training_activity.reject!
  #     @training_activity.log_activity_history('rejected', params[:comment])
  #     redirect_to training_activities_path, notice: 'Training activity rejected successfully.'
  #     TrainingActivitiesMailer.rejected(@training_activity).deliver_now
  #   end

  private

  def set_training_activity
    @training_activity = TrainingActivity.find(params[:id])
  end

  def training_activity_params
    params.require(:training_activity).permit(:name, :date, :time, :location, :priority, :justification,
                                              :unit_id, :opord_upload, competency_ids: [])
  end
end

app/helpers/training_activities_helper.rb
# frozen_string_literal: true

module TrainingActivitiesHelper
  def handle_successful_save(format)
    @training_activity.log_activity_history('activity_created')
    format.html { redirect_to @training_activity, notice: 'Training Activity was successfully created.' }
  end

  def handle_failed_save(format)
    @training_activity.competency_ids = params[:training_activity][:competency_ids].reject(&:blank?) if params[:training_activity][:competency_ids]
    format.html { render :new, status: :unprocessable_entity }
    format.turbo_stream do
      render turbo_stream: turbo_stream.replace('training_activity_form', partial: 'training_activities/form',
                                                                          locals: { training_activity: @training_activity })
    end
  end
end

app/views/training_activities/_form.html.erb
<%= form_with(model: training_activity, local: false, "data-turbo": "true", html: {class: "", id: "training_activity_form"}) do |form| %>
  <% if training_activity.errors.any? %>
    <div class="alert alert-danger" role="alert" id="error_explanation">
      <h4 class="alert-heading"><%= pluralize(training_activity.errors.count, "error") %> prohibited this training activity from being saved:</h4>
      <ul>
        <% custom_error_messages_for(training_activity).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row mb-3">
    <div class="col">
      <%= form.label :name, "Activity Name", class: "form-label" %>
      <div data-mdb-input-init class="form-outline">
        <%= form.text_field :name, required: true, class: "form-control" %>
      </div>
    </div>
    <div class="col">
      <%= form.label :date, "Activity Date", class: "form-label" %>
      <div data-mdb-input-init class="form-outline">
        <%= form.date_field :date, required: true, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <%= form.label :time, "Activity Time (Morning or Afternoon)", class: "form-label d-block" %>
      <div class="form-check form-check-inline">
        <%= form.radio_button :time, "MA", id: :time_ma, class: "form-check-input", required: true %>
        <%= form.label :time_ma, "MA", class: "form-check-label" %>
      </div>
      <div class="form-check form-check-inline">
        <%= form.radio_button :time, "AA", id: :time_aa, class: "form-check-input", required: true %>
        <%= form.label :time_aa, "AA", class: "form-check-label" %>
      </div>
    </div>
    <div class="form-outline col">
      <%= form.label :location, "Activity Location", class: "form-label" %>
      <div data-mdb-input-init class="form-outline">
        <%= form.text_field :location, required: true, class: "form-control" %>
      </div>
    </div>
  </div>
  <%= form.label :priority, "CMDT Priority", class: "form-label" %>
  <div class="select-outline">
    <%= form.select :priority, 
        [
          "Leaders of Character", 
          "Resilency Training", 
          "Military Training", 
          "Career Readiness", 
          "Physical Fitness"
        ],
        {prompt: "Choose something..."},
        {required: true, class: "select form-control", data: {mdb_select_init: true}} %>
  </div>
  <%= form.label :unit_id, "Unit", class: "form-label" %>
  <div class="select-outline">
    <%= form.select :unit_id, 
        Unit.outfit_units.map{ |unit| [unit.name, unit.id]},
        {prompt: "Choose something..."},
        {required: true, class: "select form-control", data: {mdb_select_init: true}} %>
  </div>
  <div class="mb-4">
    <label for="cr_competencies" class="form-label">CR Competencies (Max 3)</label>
    <div id="cr_competencies" class="row">
      <% Competency.all.each_slice(4) do |competency_slice| %>
        <div class="col-md-4">
          <% competency_slice.each do |competency| %>
            <div class="form-check">
              <%= check_box_tag "training_activity[competency_ids][]", 
                competency.id, 
                training_activity&.competency_ids&.include?(competency.id), 
                id: "training_activity_competencies_#{competency.id}", 
                class: "form-check-input" %>
              <%= label_tag "training_activity_competencies_#{competency.id}", 
                competency.name, 
                class: "form-check-label" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <%= form.label :justification, "Justification", class: "form-label" %>
  <div class="form-outline mb-4">
    <%= form.text_area :justification, class: "form-control", rows: 4 %>
  </div>
  <div class="mb-4">
    <%= form.label :opord_upload, "OPORD Upload", class: "form-label" %>
    <%= form.file_field :opord_upload, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/training_activities/chart.html.erb
<h1>Training Activities Chart</h1>
<%= form_tag chart_data_path, method: :get do %>
    <%= select_month(nil, { prompt: 'Select month' }, { name: 'month' }) %>
    <%= submit_tag "Filter" %>
<% end %>

<div id="chart-activities" style="height: 80vh; width: 100%;">
    <%= column_chart @data, id: 'chart-activities', stacked: true, library: { responsive: true }, colors: ["#ff0000", "#00ff00", "#0000ff", "#800000", "#007777"], title: @month_name %>
</div>

app/views/training_activities/edit.html.erb
<h1>Edit Training Activity</h1>
<%= render "form", training_activity: @training_activity %>
<br>
<%= link_to "Back", training_activities_path, class: "btn btn-secondary" %>

app/views/training_activities/index.html.erb
<div class="table-responsive">
  <table id="trainingActivitiesTable" class="table table-striped table-hover align-middle">
    <thead class="table-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Unit</th>
        <th scope="col">Date</th>
        <th scope="col" class="text-center align-middle">Time</th>
        <th scope="col">Location</th>
        <th scope="col">Priority</th>
        <th scope="col">Competencies</th>
        <th scope="col">Status</th>
        <th scope="col" class="text-center align-middle">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @training_activities.each do |training_activity| %>
        <tr>
          <td><%= training_activity.name %></td>
          <td><%= training_activity.unit.name %></td>
          <td><%= training_activity.date %></td>
          <td class="text-center align-middle"><%= training_activity.time %></td>
          <td><%= training_activity.location %></td>
          <td><%= training_activity.priority %></td>
          <td>
            <% if training_activity.competencies.any? %>
              <ul class="list-unstyled">
                <% training_activity.competencies.each do |competency| %>
                  <li><%= competency.name %></li>
                <% end %>
              </ul>
            <% else %>
              None
            <% end %>
          </td>
          <td>
            <span class="badge <%= badge_color_for_status(training_activity.aasm.human_state) %>">
              <%= training_activity.aasm.human_state %>
            </span>
          </td>
          <td class="text-center align-middle">
            <%= link_to training_activity do %>
              <%= content_tag(:i, '', class: "fa fa-eye") %>
            <% end %>
          </td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to "+", "#", class: "btn btn-success", "data-mdb-toggle" => "modal", "data-mdb-target" => "#addTrainingActivityModal", id: "addTrainingActivityButton", data: { turbo: false } %>
<!-- Modal for Adding Training Activity -->
<div class="modal fade" id="addTrainingActivityModal" tabindex="-1" aria-labelledby="addTrainingActivityModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addTrainingActivityModalLabel">Add Training Activity</h5>
        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "form", training_activity: TrainingActivity.new %>
      </div>
    </div>
  </div>
</div>
<link rel="stylesheet" href="https://uicdn.toast.com/calendar/latest/toastui-calendar.min.css" />
<script src="https://uicdn.toast.com/calendar/latest/toastui-calendar.min.js"></script>
<script>window.trainingActivities = <%= raw @training_activities.to_json %>;</script>
<script>window.units = <%= raw @units.to_json %>;</script>
<div class="d-flex justify-content-center mb-3">
  <div class="btn-group" role="group">
    <button id="viewWeekBtn" class="btn btn-outline-primary">Week</button>
    <button id="viewMonthBtn" class="btn btn-outline-primary">Month</button>
  </div>
</div>

<div class="d-flex justify-content-center mb-3">
  <div class="btn-group" role="group">
    <button id="prevBtn" class="btn btn-outline-secondary">
      <i class="fas fa-chevron-left"></i>
    </button>
    <button id="todayBtn" class="btn btn-outline-primary">Today</button>
    <button id="nextBtn" class="btn btn-outline-secondary">
      <i class="fas fa-chevron-right"></i>
    </button>
  </div>
</div>

<div class="d-flex justify-content-center mb-3">
  <div id="dateRange" class="text-center"></div>
</div>

<div class="d-flex justify-content-center">
  <div id="unitButtonsContainer"></div>
</div>
<div class="d-flex justify-content-center">
  <div id="calendar" style="height: 800px; width: 800px;"></div>
</div>

app/views/training_activities/new.html.erb
<h1>New Training Activity</h1>

<%= render "form", training_activity: @training_activity %>

<%= link_to "Back", training_activities_path %>

app/views/training_activities/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      Training Activity Details
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Name:</strong> <%= @training_activity.name %></p>
      <p class="card-text"><strong>Unit:</strong> <%= @training_activity.unit.name %></p>
      <p class="card-text"><strong>Date:</strong> <%= @training_activity.date %></p>
      <p class="card-text"><strong>Time:</strong> <%= @training_activity.time %></p>
      <p class="card-text"><strong>Location:</strong> <%= @training_activity.location %></p>
      <p class="card-text"><strong>Priority:</strong> <%= @training_activity.priority %></p>
      <p class="card-text"><strong>Justification:</strong> <%= @training_activity.justification %></p>
      <p class="card-text"><strong>Competencies:</strong></p>
      <ul class="list-group">
        <% @training_activity.competencies.each do |competency| %>
          <li class="list-group-item"><%= competency.name %></li>
        <% end %>
      </ul>
      <br>
      <p class="card-text"><strong>OPORD:</strong>
        <% if @training_activity.opord_upload.attached? %>
          <%= link_to rails_blob_path(@training_activity.opord_upload, disposition: "attachment"), class: "btn btn-primary btn-sm" do %>
            <i class="fa fa-download"></i>
          <% end %>
        <% end %>
      </p>
      <p class="badge <%= badge_color_for_status(@training_activity.aasm.human_state) %> "><strong>Status:</strong> <%= @training_activity.aasm.human_state %></p>
    </div>
    <div class="card-footer">
      <%= link_to "Edit", edit_training_activity_path(@training_activity), class: "btn btn-primary" %>
      <%= link_to "Delete", training_activity_path(@training_activity), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      <%= link_to "Back", training_activities_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>