config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Main Views
  root 'home#index'
  get 'home/index', to: 'home#index', as: 'home'
  get 'audit_activities/index'
  get 'dashboard', to: 'dashboards#index'

  # Authentication
  get '/users/:id', to: 'users#show', as: 'user'
  get '/logout', to: 'sessions#logout', as: 'logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/training_activities/chart', to: 'training_activities#chart_data', as: 'chart_data'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :training_activities
  resources :user
  resources :audit_activities do
    member do
      post :approve
      post :improve
      post :reject
      post :resubmit
      post :cancel
    end
  end
  resources :admin do
    collection do
      post :import
      post :stop_impersonate
    end
    member do
      post :impersonate
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Mailer
  mount LetterOpenerWeb::Engine, at: '/letter_opener'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadetActivityManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% unless controller_name == 'home' && action_name == 'index' %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
          <div class="container-fluid">
            <button
              data-mdb-collapse-init
              class="navbar-toggler"
              type="button"
              data-mdb-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <a class="navbar-brand" href="<%= home_path %>">
                <%= image_tag('tamu-logo.png', height: '25', alt: 'App Logo', loading: 'lazy') %>
              </a>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" href="<%= training_activities_path %>">
                    Training Activities
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= audit_activities_path %>">
                    Audit Activities
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= chart_data_path %>">
                    Statistical Charts
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= admin_index_path %>">
                    Admin
                  </a>
                </li>
                <% if session[:admin_id].present? && session[:admin_id] != session[:user_id] %>
                  <li class="nav-item">
                    <%= form_tag stop_impersonate_admin_index_path, method: :post do %>
                      <%= submit_tag "Stop Impersonation", class: "btn btn-danger" %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="d-flex align-items-center">
              <div class="dropdown">
                <a data-mdb-dropdown-init
                  class="dropdown-toggle d-flex align-items-center hidden-arrow"
                  href="#"
                  id="navbarDropdownMenuAvatar"
                  role="button"
                  aria-expanded="false"
                  data-turbo="false"
                >
                  <%= image_tag(current_user.profile_picture.present? ? current_user.profile_picture : 'blank-profile-picture.png', class: "rounded-circle", height: "25", alt: "User Profile Picture", loading: "lazy") %>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
                  <li>
                    <a class="dropdown-item" href="<%= user_path(@current_user) %>">My Profile</a>
                  </li>
                  <%= button_to logout_path, method: :get, class: "dropdown-item" do %>
                    <i class="fas fa-sign-out-alt"></i> Logout
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </header>
    <% end %>
    <main class="<%= 'main-content' unless controller_name == 'home' && action_name == 'index' %>">
      <%= render partial: "shared/display_flash" unless flash.empty? %>
      <%= yield %>
    </main>
  </body>
</html>